apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/ralucamihale/ci_cd_lab@sha256:93cf93f6e9c66ba84a9bf158db74d712598439bb394055126044f59b37822c6b
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
